### ISSUE TITLE
Hamburger button is not displayed when launch on Pixel 4.

### ISSUE THREAD

**Issue by xybertom** [TwidereProject/Twidere-Android#1223]
Hamburger button is not displayed when launch on Pixel 4.
so, I can't use side menu with new Android navigation.

## Expected behavior
Hamburger button is displayed.

## Actual behavior
Hamburger button is not displayed.

## Steps to reproduce
Launch app on pixel 4.

## Extra info

Android version: (version code here)
Android 10 QD1A.190821.007

Network type:

- [ ] Cellular
- [x] Wi-Fi

App version: (version code here)
3.7.8

Build variant:

- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ ] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by mariotaku** [comment]
Solution for fixing: Use latest navigation drawer library to be compatible with gesture navigation @Tedko @Tlaster

**Comment by kg8m** [comment]
I had same issue. Temporarily, I resolved this issue as following:

  1. Open "Settings" app
  1. Go to "System"
  1. Go to "Gestures"
  1. Go to "System navigation"
  1. Activate "3-button navigation"
  1. Open "Twidere" app
  1. Swipe at the left edge (the side menu opens)
  1. Go to "Settings"
  1. Activate "Drawer toggle"
  1. Restart "Twidere" app (the hamburger button appears)
  1. Use the side menu via the hamburger button

**Comment by Tedko** [comment]
Fixed by https://github.com/TwidereProject/Twidere-Android/commit/4bc560e8d3ea5e7db03c2bc0fdbdd41a516e4d52

**Comment by rugk** [comment]
Still does not work in Twidere 4.1.4? It's not displayed on my FP3.
